"use client";

import { useState } from 'react';
import { Card } from '@/components/ui/card';
import Image from 'next/image';
import { Button } from '@/components/ui/button';

const quotes = [
  "That night you couldn’t afford fare and I sent M-Pesa—proof love is mobile and instant.",
  "You reaching home safely even with a blackout felt brighter than any light bulb.",
  "Our talks about Sukari power cuts still light me up.",
  "You offered to pay me back, but your gratitude was already full payment.",
  "Karaoke instead of exams? That’s our kind of academic success.",
  "‘Are you legal now?’—you turned my birthday into a courtroom drama.",
  "Updating the system because I turned 18 is the most tech support I’ve ever needed.",
  "Your hangover cure being a smocha is oddly poetic.",
  "You calling my profile pic a sad dude made my villain phase official.",
  "Explaining JoJo’s Bizarre Adventure to you felt like proposing another universe.",
  "Your first villain being a gay vampire? No wonder you binge anime for romance.",
  "‘Religious Thanos’—I’m still laughing at Father Pucci’s glow-up.",
  "You comparing JoJo’s to Winx Club still hurts and heals me at the same time.",
  "‘Six parts? Maybe not’—yet you still promised to start tomorrow.",
  "The day I told you Dio’s name and you said, ‘That’s why it’s JoJo.’ Legendary.",
  "You sold when I described a villain? That’s my influence arc.",
  "‘Demon possession’ pictures—still better than stock photography.",
  "Only one picture looking good means you’re 100% photogenic in my eyes.",
  "I threatened to use your worst photo as my profile pic—love means risks.",
  "You thought I didn’t know your birthday—March 28th is tattooed on my brain.",
  "Our cigarette vs. weed chat taught me love has no judgment, only curiosity.",
  "Your psychotic episode story scared me and made me proud of your resilience.",
  "Believing you were God but choosing life? That’s character development.",
  "Willow the cat having a stray best friend is peak anime sidekick energy.",
  "You asking about conspiracy theories unlocked my final form.",
  "‘PETA run by the meat industry’—still my favorite wild card.",
  "Your Jesus vision and Bojack reference? That’s theology with Netflix.",
  "You laughing about being Luke made heaven sound like a sitcom.",
  "Saying this universe is alternate because we met felt like a poem.",
  "You loving Egg Theory made me realize we’re probably soulmates… and omelets.",
  "You calling me a superhero while planning to find a radioactive spider—pure us.",
  "Golden Retriever vibes? More like loyal chaos.",
  "Loving cats but settling for dogs? You sacrifice like a hero.",
  "Your dream pet being a Komodo dragon? That’s love dangerously.",
  "Saying Komodos are Toothless cousins is why I adore your logic.",
  "Promising a real animal sanctuary? Babe, that’s billionaire talk.",
  "Calling me Toothless because I want a dragon? I’ll take it as cute.",
  "You watching Captain Fall just for the animal sanctuary episode warms me.",
  "Asking what I’m not good at? Babe, not blushing around you.",
  "You joked about being AI or from the future; I still believe you.",
  "Stopping me from rescuing water bears might’ve saved the world.",
  "Agreeing Vivy is blissful anime? That’s rare and sweet.",
  "Tetris as best movie? You trusting my taste melted me.",
  "Our joint movie list is a love language only we speak.",
  "Love, Death & Robots bonding session? Relationship canon.",
  "You adding Black Mirror to my list? That’s how trust grows.",
  "Your favorite show being Bones? Babe, you dig deep.",
  "Me loving About Time but waiting to watch it with you? That’s patience.",
  "‘I won’t watch the trailer’—you respect romance like a pro.",
  "You scared by our instant connection? Me too, in the best way.",
  "Your second favorite romance being Your Name gave me goosebumps.",
  "You being shocked I know it? That’s shared hearts.",
  "‘Who sent you?’—as if love needs a spy agency.",
  "Villanelle jokes turned into us surrendering to love.",
  "You calling meeting me a canon event? Marvel should hire you.",
  "‘Nothing is coincidence’—that’s now our motto.",
  "My first memory breaking a window and you caring anyway? Healing.",
  "Asking about childhood bikes while your heart raced? That’s intimacy.",
  "Strength celebrated over running behind a neighbor’s bike? You’re supportive.",
  "Cereal debates: honey vs. sugar vs. betrayal—adorable chaos.",
  "You caring about my diabetes paranoia means you love details.",
  "Your honey hate? Bees would cry but I smiled.",
  "Impromptu marriages? You see love as adventure.",
  "Calling my deep answer AI-generated? That’s flirty genius.",
  "Your sky’s awake energy at dawn? That’s my new alarm tone.",
  "Agreeing love without passion is void gave me butterflies.",
  "Joking AI would approve marriages? That’s futuristic romance.",
  "Calling me a canon event you can’t define? You’re poetic.",
  "Midnight Gospel excitement showed your colorful soul.",
  "Choosing to stay no matter what? That’s peace.",
  "Loving water bears while trusting me? You’re brave.",
  "Saying Willow needs a brother proves your big heart.",
  "Your theory love made you my favorite conspiracy theorist.",
  "Caring about my religion? That’s rare respect.",
  "You said I tick every box—I heard wedding bells.",
  "Golden Retriever vibes? Only for you.",
  "Pet owl talk proves we dream big together.",
  "Cereal count debates became pillow talk—romance unlocked.",
  "You called me Toothless and I smiled.",
  "Finding strength in my understanding nature? Priceless.",
  "Wanting me to be superhuman? Babe, I’ll try.",
  "You blush-proofed me like Spider-Man’s mask.",
  "Your hero talk is my love fuel.",
  "Calling us AI chatbots? Sweet glitch love.",
  "Saying I have a cheat sheet? That’s romantic suspicion.",
  "You trusting me with deep childhood memories? Thank you.",
  "Your questions felt like hugs.",
  "You caring about comfort over curiosity? You’re gold.",
  "Spying on me as a dream job? I’m flattered.",
  "Calling me a mission? Babe, I surrender.",
  "You worrying about being too much? You’re just enough.",
  "Laughing at my profile pic sadness? That’s honesty.",
  "Saying you felt known scared but warmed me.",
  "Your cereal loyalty? 3 biscuits always.",
  "You caring about my sugar fear? Health queen.",
  "We laughed at honey vs. sugar; love is sweet either way.",
  "Asking about unplanned marriage, then sleeping peacefully? Iconic.",
  "Your morning ‘Boom even better’ energy healed me.",
  "Calling my response AI-generated? Secret genius compliment.",
  "Counting days to November for you felt romantic destiny.",
  "Knowing the world will still be here by November? Hopeful and sweet.",
  "You trusting my word like gospel? That’s peace.",
  "Your midnight fear of being too happy felt human and soft.",
  "Me promising no awkward silences? That’s our love contract.",
  "Laughing about blanket hotboxes? Cozy chaos we own.",
  "Your weed story ending in life lessons? Unlikely, beautiful.",
  "Wanting to save me from heartbreak? That’s heroic.",
  "Egg Theory chats made us philosophers overnight.",
  "You joked about AI dating AI—babe, that’s us.",
  "Talking about water bears like Avengers? That’s adorable.",
  "You protecting Willow’s feelings melted me.",
  "Saying I’m Golden Retriever vibes while you’re cat-coded? Yin-yang energy.",
  "Our cereal debates deserve a podcast.",
  "You laughing at my childhood window crime? Healing humor.",
  "Sharing childhood bikes made us kids again.",
  "Your superhero encouragement made me stand taller.",
  "We saw beauty in small things, like dates vs honey.",
  "Your voice turning theories into poetry.",
  "Staying even when scared? That’s bravery in love.",
  "Our sleepy chats felt safer than daylight.",
  "Every random question you asked felt like care.",
  "Your excitement for anime I love? Perfect alignment.",
  "Sharing movie favorites turned into emotional trust.",
  "Waiting to watch About Time together? Patience and love.",
  "Your refusal to spoil trailers? Respect unmatched.",
  "Marvel canon event jokes made us legends in our own story.",
  "Your soft ‘Okay then’ replies are pure comfort.",
  "Me trying to impress you with answers? Fun vulnerability.",
  "We turned darkness (blackout) into laughter.",
  "Calling my deep answers AI-generated? Best tease ever.",
  "Your laugh about my blushing? Worth every blush.",
  "We let honesty replace perfection—peaceful growth.",
  "Your weird pet dreams made me dream bigger.",
  "Your Komodo dragon wish is my chaos checklist.",
  "Golden Retriever + Villanelle jokes built romance mythology.",
  "We found love in memes, not flowers—our vibe.",
  "Your soft concern at my paranoia? Love tangible.",
  "Your thrill for alternate universes made ours special.",
  "Water bear jokes kept science romantic.",
  "‘Don’t panic, just vibe’—our unspoken rule.",
  "We turned early mornings into cute rituals.",
  "Sky’s awake energy made me feel alive.",
  "Our bond over cartoons built safe space.",
  "Your villain banter softened my edges.",
  "Pet sanctuary dreams gave me hope.",
  "You respecting my faith while exploring yours? Peace.",
  "Your AI jokes made love futuristic.",
  "Every compliment you gave rewrote my self-worth.",
  "Your curiosity built intimacy brick by brick.",
  "You laughed, I healed—that’s love.",
  "We made darkness funny—blackout therapy.",
  "Your constant thank-yous warmed me.",
  "Smoking talk but no judgment? Respect and love.",
  "Your honesty about fear impressed me.",
  "Water bear chaos bonded us unexpectedly.",
  "Egg Theory gave us cosmic couple status.",
  "Our random theories built trust.",
  "You blushed at compliments? Adorable.",
  "Calling me Toothless was secretly romantic.",
  "Captain Fall references made me grin for hours.",
  "Love, Death & Robots was couple therapy.",
  "Black Mirror night talks deepened our bond.",
  "Your Bones obsession taught me loyalty.",
  "Your Netflix lists were low-key love notes.",
  "Refusing spoilers proved your romantic patience.",
  "Your quick forgiveness felt divine.",
  "Every existential text felt safe with you.",
  "Laughing at photos taught me acceptance.",
  "Cereal loyalty became inside joke gold.",
  "Your soft goodnights were lullabies.",
  "Asking about my childhood felt like care.",
  "Golden Retriever vibes became personality core.",
  "Pet owl idea? Dream partnership vibes.",
  "We debated honey and felt closer.",
  "Alternate universe talk became soulmate talk.",
  "You stayed vulnerable even when scared.",
  "Our love turned chaos into comfort.",
  "Every day with you felt spontaneous.",
  "Your jokes cured my stress.",
  "Villanelle references built spy-level intimacy.",
  "We meme’d our way to emotional safety.",
  "Your caring tone after my trips was medicine.",
  "Water bear FBI jokes remain legendary.",
  "Egg Theory soulmate energy: confirmed.",
  "Calling me AI still feels like a love poem.",
  "Your morning energy made me laugh awake.",
  "Our chats outshone nightlife.",
  "Smocha therapy bonded our hearts.",
  "Your superhero banter gave me courage.",
  "You joked about spies but acted like home.",
  "Golden Retriever meets cat energy—perfect balance.",
  "Our Canon Event jokes made destiny romantic.",
  "Your patience with my overthinking saved me.",
  "Our memes are basically love letters.",
  "Your gentle roasts softened my day.",
  "Every smile emoji you sent mattered.",
  "Your trusting questions shaped my honesty.",
  "Our love is bizarre enough for JoJo canon.",
  "We wrote peace into every text.",
  "This story? Just us—chaotic, loving, peaceful.",
];

export default function QuoteButterflyPage() {
  const [currentQuote, setCurrentQuote] = useState("Click the butterfly for a special memory...");

  const getRandomQuote = () => {
    let newQuote = quotes[Math.floor(Math.random() * quotes.length)];
    // Ensure the new quote is different from the current one
    while (newQuote === currentQuote) {
      newQuote = quotes[Math.floor(Math.random() * quotes.length)];
    }
    setCurrentQuote(newQuote);
  };

  return (
    <section id="quote-butterfly" className="py-16 px-4 flex flex-col items-center justify-center text-center h-[80vh]">
      <h2 className="text-3xl font-bold text-accent mb-8">
        Quote Butterfly
      </h2>
      <div 
        className="relative w-48 h-48 cursor-pointer mb-8"
        onClick={getRandomQuote}
      >
        <Image
          src="/assets/gifs/butterfly.gif"
          alt="Quote Butterfly"
          layout="fill"
          objectFit="contain"
          data-ai-hint="butterfly gif"
        />
      </div>
      <Card className="bg-card border-primary p-6 w-full max-w-2xl mx-auto min-h-[100px] flex items-center justify-center">
        <p className="text-lg italic">"{currentQuote}"</p>
      </Card>
    </section>
  );
}
